#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H
#include <QRectF>

const float GAMEWINDOW_SIZE = 900;
const float LEFT_BOARD_X = 0, RIGHT_BOARD_X = GAMEWINDOW_SIZE, DEFAULT_VERTICAL_PADDING = 0.05 * GAMEWINDOW_SIZE;
const float STATUS_TEXT_WIDTH = GAMEWINDOW_SIZE * 0.3;
const float TEXT_PADDING = GAMEWINDOW_SIZE * 0.02;
const QRectF leftOutOfGamewindow = QRectF(-GAMEWINDOW_SIZE, 0, GAMEWINDOW_SIZE, GAMEWINDOW_SIZE);
const QRectF rightOutOfGamewindow = QRectF(GAMEWINDOW_SIZE, 0, GAMEWINDOW_SIZE, GAMEWINDOW_SIZE);
const QRectF upOutOfGamewindow = QRectF(0, -GAMEWINDOW_SIZE, GAMEWINDOW_SIZE, GAMEWINDOW_SIZE);
const QRectF downOutOfGamewindow = QRectF(0, GAMEWINDOW_SIZE, GAMEWINDOW_SIZE, GAMEWINDOW_SIZE);
#endif // GAME_CONSTANTS_H
